using UnityEngine;
using UnityEngine.EventSystems;

/// <summary>
/// Generated by ChatGPT: https://chatgpt.com/share/67955eda-0cc4-8002-9d5b-1777d7eabc2e
/// </summary>
public class ButtonEffects : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler, IPointerDownHandler, IPointerUpHandler
{
    public Vector3 hoverScale = new Vector3(1.1f, 1.1f, 1.1f); // Scale when hovered
    public Vector3 pressedScale = new Vector3(0.9f, 0.9f, 0.9f); // Scale when pressed
    private Vector3 originalScale; // To store the original scale

    private void Start()
    {
        // Save the button's original scale
        originalScale = transform.localScale;
    }

    public void OnPointerEnter(PointerEventData eventData)
    {
        // Increase the button's size slightly when hovered
        transform.localScale = hoverScale;
    }

    public void OnPointerExit(PointerEventData eventData)
    {
        // Return to the original size when the cursor leaves the button
        transform.localScale = originalScale;
    }

    public void OnPointerDown(PointerEventData eventData)
    {
        // Decrease the button's size slightly when pressed
        transform.localScale = pressedScale;
    }

    public void OnPointerUp(PointerEventData eventData)
    {
        // Return to hover size if still hovered, else original size
        transform.localScale = RectTransformUtility.RectangleContainsScreenPoint(
            GetComponent<RectTransform>(),
            eventData.position,
            eventData.pressEventCamera) ? hoverScale : originalScale;
    }
}